proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include
from proyecto1.views import today, saludo, probandoTemplate, testTemplate
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("saludo/", saludo),
    path("day/", today),
    path("probandoTemplate/",probandoTemplate),
    path('C:/Users/Alan/Desktop/PythonProyecto1/proyecto1/static/admin/css/style/style.css', views.css_file, name='css_file'),
    path("test/", testTemplate),
    path("prueba/", include("prueba.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba/urls.py
from django.urls import path
from prueba import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static



app_name = 'prueba'

urlpatterns = [
    path("browse/", views.browse),
    path("index/", views.index),
    path("profile/<user>", views.profile,name = "Profile"),
    path("Details/", views.details),
    path("streams/", views.streams),
    path("login/", LoginView.as_view(template_name='Login_Final_Proyect.html'), name= "Login"),
    path("home/", views.Home, name= "home"), 
    path("register/",views.Register_Final, name="Registro"),
    path("about/", views.about),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('post/', views.create_post, name='create_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path("detail/<int:post_id>", views.post_detail, name='detail'),
    path("edit/", views.profile_edit, name="edit"),
    path("inbox/", views.inbox, name='inbox'),
    path('sent/', views.sent, name='sent'),
    path('compose/', views.compose, name='compose_with_recipient'),
    path('message/<int:message_id>/', views.message_detail, name='message_detail'),
    path('avatar/', views.avatar_change, name='avatar'),
    path('postlist/', views.post_list, name='post_list'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, User
from django.conf import settings

# Create your models here.

class Register_AccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, username, password)

class Register_Account(AbstractBaseUser):
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = Register_AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'password']

    def __str__(self):
        return self.email


class Login_Account(models.Model):
    objects = Register_AccountManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'password1']

    def __str__(self):
        return self.email
    

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)


class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='avatar')
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.image}"
        
    class Meta:
        unique_together = ('user',)
    

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    subject = models.CharField(max_length=255)
    body = models.TextField()
    sent_date = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.sender} - {self.receiver}: {self.subject}"

prueba/forms.py
from django import forms
from django.http import HttpResponse
from django.shortcuts import render
from .models import Login_Account,Register_Account, Post, User, Message, Avatar
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import gettext_lazy as _

def search(request):
    search_query = request.GET.get('search_query')
    # Aquí implemente su lógica de búsqueda
    return render(request, 'search_results.html', {'search_query': search_query})


class SearchForm(forms.Form):
    name = forms.CharField()
    ingredients = forms.CharField()
    description = forms.CharField()



class RegisterForm(UserCreationForm):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    

    class Meta:
        model = Register_Account
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

class Login_account_Form(forms.ModelForm):
    class Meta:
        username = forms.CharField(max_length=50)
        password = forms.CharField(max_length=50)
        model = Login_Account
        fields = "__all__"


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','subtitle','description','image']


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Register_Account
        fields = ['username','email','password']
        exclude = ['last_login', 'last_name','first_name']

class AvatarChange(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ['image']

class MessageForm(forms.ModelForm):
    receiver = forms.ModelChoiceField(queryset=User.objects.all(), empty_label='Choose a user')

    class Meta:
        model = Message
        fields = ['receiver', 'subject', 'body']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        }

prueba/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Template, Context
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .forms import RegisterForm, PostForm, EditProfileForm, MessageForm, AvatarChange
from django import forms
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.contrib.auth.views import logout_then_login
from .models import Post, Message, Avatar
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.utils import timezone

# Create your views here.

@login_required
def index(request):
    latest_posts = Post.objects.order_by('pub_date')[:10]
    user = request.user
    avatar = None  # Asignar un valor predeterminado
    try:
        avatar = Avatar.objects.get(user=request.user)
    except Avatar.DoesNotExist:
        pass
    context = {'latest_posts': latest_posts,'usuario':user,'avatar':avatar}
    return render(request, "index.html", context)

def details(request):
    return render (request, "details.html")

@login_required
def profile(request, user):
    user = request.user
    num_posts = Post.objects.filter(author=user).count()
    email = request.user.email
    user_posts = Post.objects.filter(author=user)
    context = {'num_posts': num_posts, 'email': email,'user_posts':user_posts}

    try:
        avatar = Avatar.objects.get(user=request.user)
        context['avatar'] = avatar
    except Avatar.DoesNotExist:
        pass

    return render(request, "profile.html", context)
   

def browse(request):
    return render (request, "browse.html")

def streams(request):
    return render (request, "streams.html")

def Login_Final(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)

        if form.is_valid():
            user = form.cleaned_data.get("username")
            password = form.cleaned.data_get('password')
            
            user = authenticate(username=user,password=password)
            
            if user is not None:
                login(request, user)

                next_url = request.GET.get('next', '')
                if next_url:
                    return redirect(next_url)

                return redirect(request, "../index/", {"mensaje": f"Welcome {user}"})
            else:
                return render(request,"respuesta.html",{"mensaje":"Error,datos incorrectos"})
        else:
                return render(request, "respuesta.html", {"mensaje": "Error, formulario erroneo"})
    
    form = AuthenticationForm()

    return render(request, "Login_Final_Proyect.html",{'form':form})

def Home(request):
    latest_posts = Post.objects.order_by('pub_date')[:10]
    user = request.user
    context = {'latest_posts': latest_posts,'usuario':user}
    return render(request, "home.html", context)

def about(request):
    return render(request, "about.html")

def Register_Final(request):
    if request.method == 'POST':
        # obtener los datos del formulario
        username = request.POST['username']
        password = request.POST['password1']
        email = request.POST['email']

        # verificar si el nombre de usuario ya está en uso
        if User.objects.filter(username=username).exists():
            return render(request, 'Register_Final.html', {'form': RegisterForm(), 'error': 'El nombre de usuario ya está en uso.'})

        # crear el usuario
        else:
            user = User.objects.create_user(username, email, password)
            user.save()

        # autenticar al usuario y redirigirlo a la página de inicio
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('../index/')
        else:
            # mostrar un mensaje de error si las credenciales son incorrectas
            return render(request, 'Register_Final.html', {'form': RegisterForm(), 'error': 'Error al autenticar al usuario.'})
    else:
        form = RegisterForm()
    return render(request, 'Register_Final.html', {'form': form})

@method_decorator(login_required, name='dispatch')
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        return logout_then_login(request, login_url=reverse_lazy('home'))

#return redirect('prueba:profile', user=request.user.username)
@login_required
def avatar_change(request):
    avatar = None
    if request.method == 'POST':
        form = AvatarChange(request.POST, request.FILES)
        if form.is_valid():
            avatar, created = Avatar.objects.update_or_create(
                user=request.user,
                defaults={'image': form.cleaned_data['image']}
            )
            return redirect(f'../profile/{request.user.username}')
    else:
        form = AvatarChange()
        try:
            avatar = Avatar.objects.get(user=request.user)
        except Avatar.DoesNotExist:
            pass
    return render(request, 'avatar_change.html', {'form': form, 'avatar': avatar})



@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post_url = reverse('prueba:detail', args=[post.id])
            return redirect(post_url)
    else: 
        form = PostForm()
    try:
        avatar = Avatar.objects.get(user=request.user)
    except Avatar.DoesNotExist:
        pass
    return render(request, 'create_post.html', {'form':form,'avatar':avatar})

@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    try:
        avatar = Avatar.objects.get(user=request.user)
    except Avatar.DoesNotExist:
        pass
    
    return render(request, 'post_detail.html', {'post':post,'avatar':avatar})


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('post_detail', post_id=post.id)
    return render(request, 'post_detail.html', {'form': form})
@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect('prueba:post_list')

def post_list(request):
    latest_posts = Post.objects.order_by('pub_date')[::1]
    user = request.user
    try:
        avatar = Avatar.objects.get(user=request.user)
    except Avatar.DoesNotExist:
        pass
    context = {'latest_posts': latest_posts,'usuario':user,'avatar':avatar}
    return render(request, 'post_list.html', context)


@login_required
def profile_edit(request):
    if request.method == 'POST':
        username = RegisterForm(user=request.user, data=request.POST)
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save(), username.save()
            update_session_auth_hash(request, user)
            messages.success(request, '¡Tu perfil ha sido actualizado con éxito!')
            return redirect('prueba:profile')
        else:
            messages.error(request, 'Por favor corrija los errores a continuación')
    else:
        form = PasswordChangeForm(user=request.user)
    try:
        avatar = Avatar.objects.get(user=request.user)
    except Avatar.DoesNotExist:
        pass
    return render(request, 'profile_edit.html', {'form': form,'avatar':avatar})
#COMPLETO>>>



@login_required
def inbox(request):
    messages = Message.objects.filter(receiver=request.user)
    try:
        avatar = Avatar.objects.get(user=request.user)
    except Avatar.DoesNotExist:
        pass
    context = {'messages': messages,'avatar':avatar}
    return render(request, 'inbox.html', context)

@login_required
def sent(request):
    messages_sent = request.user.sent_messages.all().order_by('-sent_date')
    return render(request, 'sent.html', {'messages_sent': messages_sent})

@login_required
def compose(request, recipient=None):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            message.sent_date = timezone.now()
            message.read = False
            message.save()
            messages.success(request, 'Message sent successfully')
            return HttpResponseRedirect(reverse('prueba:inbox'))
    else:
        form = MessageForm(initial={'receiver': recipient})
    try:
        avatar = Avatar.objects.get(user=request.user)
    except Avatar.DoesNotExist:
        pass
    return render(request, 'compose.html', {'form': form,'avatar':avatar})

@login_required
def message_detail(request, message_id):
    message = get_object_or_404(Message, id=message_id)
    if message.receiver == request.user:
        message.read = True
        message.save()
    try:
        avatar = Avatar.objects.get(user=request.user)
    except Avatar.DoesNotExist:
        pass
    return render(request, 'message_detail.html', {'message': message,'avatar':avatar})


@login_required
def create_message(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            # Obtener datos del formulario
            subject = form.cleaned_data['subject']
            body = form.cleaned_data['body']

prueba/templates/Login_Final_Proyect.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Cyborg - Awesome HTML5 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static '/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static '/css/templatemo-cyborg-gaming.css' %}">
    <link rel="stylesheet" href="{% static '/css/owl.css' %}">
    <link rel="stylesheet" href="{% static '/css/animate.css' %}">
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
<!--

TemplateMo 579 Cyborg Gaming

https://templatemo.com/tm-579-cyborg-gaming

-->
  </head>

<body>

  <!-- ***** Preloader Start ***** -->

  <!-- ***** Preloader End ***** -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    {% if user.is_authenticated %}
                    <a href="../index/" class="logo">
                        <img src="{% static 'assets/img/logo.png' %}" alt="">
                    {% else %}
                    <a href="../home/" class="logo">
                      <img src="{% static 'assets/img/logo.png' %}" alt="">
                    {% endif %}
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    {% if user.is_authenticated %}
                    <ul class="nav">
                        <li><a href="../index/">Home</a></li>
                    {% else %}
                    <ul class="nav">
                      <li><a href="../home/">Home</a></li>
                    {% endif %}
                    </ul>   
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->
  <main style="position: fixed;top: 50%;display: flex;flex-direction: column;justify-content: center;align-items: center;left: 50%;transform: translate(-50%, -50%);" >
    <style>
      p {
        color: black;
        margin-top:10px;
      }
      input[type="submit"] {
      display: block;
      margin: auto;
      margin-top: 10px; /* Ajusta el valor de margin-top según sea necesario */
      }
      .register-link{
        float: right;
        margin-top:-25px;
      }
    </style>
    <div style="padding: 30px;background-color: #cddc39;border-radius:10px;box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.5);">
      <form method="POST" action="">
        {% csrf_token %}
            {{ form.as_p}}
        <input type="submit" value="Login" style="border-radius:5px;color:white;background-color:black"> 
            {% if user.is_authenticated %}
              <input type="hidden" name="next" value="../index/">
            {% endif %}
        <a class="register-link" href="../register" style="color:grey;">Register</a>
      </form>
    </div>
  </main>
  
  
  <footer>
    <div class="container" style ="position: fixed;bottom: 0;right: 0;">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2036 <a href="#">Cyborg Gaming</a> Company. All rights reserved. 
          
          <br>Design: <a href="https://templatemo.com" target="_blank" title="free CSS templates">TemplateMo</a>  Distributed By <a href="https://themewagon.com" target="_blank" >ThemeWagon</a></p>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>

  <script src="{% static '/js/isotope.min.js' %}"></script>
  <script src="{% static '/js/owl-carousel.js' %}"></script>
  <script src="{% static '/js/tabs.js' %}"></script>
  <script src="{% static '/js/popup.js' %}"></script>
  <script src="{% static '/js/custom.js' %}"></script>


  </body>

</html>

prueba/templates/avatar_change.html
{% extends 'Plantilla.html' %}


{% block content %}
    <form method="post" enctype="multipart/form-data">     
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-primary">Apply changes</button>
    </form>
{% endblock %}

prueba/templates/compose.html
{% extends 'Plantilla.html' %}

{% block content %}
    <h1>Send Message</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
{% endblock %}

prueba/templates/inbox.html
{% extends 'Plantilla.html' %}

{% block content %}
    <h1>Inbox</h1>
    <ul>
        {% for message in messages %}
    <li>
        {% if message.id %}
            <a href="{% url 'prueba:message_detail' message.id %}">
                {{ message.subject }} - {{ message.body }}
            </a>
        {% else %}
            {{ message.subject }} - {{ message.body }}
        {% endif %}
    </li>
{% endfor %}
    </ul>
{% endblock %}

prueba/templates/message_detail.html
{% extends 'Plantilla.html'%}

{% block content %}

  <h3>De: {{ message.sender }}</h3>
  <h3>Asunto: {{ message.subject }}</h3>
  <h3>{{ message.body }}</h3>
  <p>{{ message.sent_date }}</p>

{% endblock %}

prueba/templates/post_detail.html
{% extends "Plantilla.html" %}

{% block content %}
    <div class="post-container" style="display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    margin-top: 50px;">
        {% if user.is_authenticated %}
        <a href="{% url 'prueba:delete_post' post_id=post.id %}">Eliminar</a>
        {% endif %}

        <div class="post-header" style= "display: flex;
        align-items: center">
        <img src="{{ post.author.avatar.image.url }}" alt="{{ post.author.username }}" class="profile-image" style ="  width: 50px;
        height: 50px;
        border-radius: 50%;
        margin-right: 10px;">
        <h4 class="post-author">{{ post.author.username }}</h4>
        </div>
        <div class="post-image-container" style="margin-top: 20px;
        text-align: center;">
        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image" style= "  width: 500px;
        max-width: 100%; border-radius: 20px;">
        </div>
        <div class="post-description" style=" margin-top: 20px;
        text-align: justify">
        <p style="font-size:20px">{{ post.description }}</p>
        <p class="post-date" style="font-style: italic;font-size: 18px ;
        margin-top: 10px;">{{ post.pub_date }}</p>
        </div>
    </div> 
{% endblock %}

prueba/templates/profile.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Cyborg - Awesome HTML5 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    
    
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static '/css/fontawesome.css'%}">
    <link rel="stylesheet" href="{% static '/css/templatemo-cyborg-gaming.css'%}">
    <link rel="stylesheet" href="{% static '/css/owl.css'%}">
    <link rel="stylesheet" href="{% static '/css/animate.css'%}">
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static '/css/Propio.css'%}">
<!--

TemplateMo 579 Cyborg Gaming

https://templatemo.com/tm-579-cyborg-gaming

-->
  </head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="../index/" class="logo">
                        <img src="{% static 'assets/img/logo.png'%}" alt="">
                    </a>
                    <!-- ***** Logo End ***** -->
                    
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="../index/">Home</a></li>
                        <li><a href="../post/">Post</a></li>
                        <li><a href="../compose/">Direct Message</a></li>
                        <li><a href="../inbox/">Inbox</a></li>
                        <li><a href="{% url 'prueba:logout' %}" class="active">Logout</a></li>
                    </ul>   
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="page-content">

          <!-- ***** Banner Start ***** -->
          <div class="row">
            <div class="col-lg-12">
              <div class="main-profile ">
                <div class="row">
                  <div class="col-lg-4">
                    {% if not avatar %}
                    <li><a href="../profile/{{ usuario }}">{{ user.username }}{% if avatar.image %} <img src="{{ avatar.image.url }}" alt="">{% endif %}</a></li>
                    {% endif %}
                    {% if avatar %}
                        <img src="{{ avatar.image.url }}" alt="{{ request.user.username }}" style="border-radius: 23px;">
                    {% else %}
                        <img src="{% static 'assets/img/profile.jpg' %}" alt="{{ request.user.username }}" style="border-radius: 23px;">
                    {% endif %}
                  </div>
                  <div class="col-lg-4 align-self-center">
                    <div class="main-info header-text">
                      {% if user.is_authenticated %}
                      <span style="background-color: #cddc39;color:black;">Online</span>
                      {% else %}
                      <span>Offline</span>
                      {% endif %}
                      {% if user.is_authenticated %}
                        <a style="opacity:0;position:absolute;left:0px;top:100%;"href ="https://media.meer.com/attachments/78314690338eb7bd8aaa4fef32d315c0111851bf/store/fill/1090/613/299f10c060ccbe8314f51a969c67a6be1956221f5f3fab2adb4c314235a2/Bonobos.jpg"><p>p</p></a>
                      {% endif %}
                      <p></p>
                      {% if user.is_authenticated %}
                      <div class="main-border-button">
                        <a href="../avatar/">Change Your avatar</a>
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  <div class="col-lg-4 align-self-center">
                    <ul>
                      <li>{% if user.is_authenticated %}
                         <p class="username-profile">{{ user.username }}</p>
                        {% endif %}</li>
                      <li class="post-count-conteiner">
                        {% if user.is_authenticated %}
                         <p>Numero de post</p>
                         <span>{{ num_posts }}<span>
                        {% endif %}
                      </li>
                      <li class="post-count-conteiner">
                        Email 
                        {% if user.is_authenticated %}
                          <p class="Datos_Tabla_Perfil">{{ email }} </p>
                        {% endif %}
                      </li>
                      <li><a href="../edit/" class="Editar-Perfil">Editar Perfil</a></li>
                    </ul>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-12">
                    <div class="clips">
                      <div class="row">
                        <div class="col-lg-12">
                          <div class="heading-section">
                            <h4>Your Posts</h4>
                          </div>
                        </div>
                        <div class="image-grid">
                          {% for post in user_posts %}
                              <div class="image-item" >
                                  <img src="{{ post.image.url }}" alt="{{ post.title }}">
                              </div>
                          {% endfor %}
                      </div>
                        
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- ***** Banner End ***** -->

          <!-- ***** Gaming Library Start ***** -->
          
          <!-- ***** Gaming Library End ***** -->
        </div>
      </div>
    </div>
  </div>
       
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Here is some things <a href="../about/">About Me</a>
          
            <br>2023</br>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static '/assets/jquery/jquery.min.js'%}"></script>
  <script src="{% static '/bootstrap/js/bootstrap.min.js'%}"></script>

  <script src="{% static '/js/isotope.min.js'%}"></script>
  <script src="{% static '/js/owl-carousel.js'%}"></script>
  <script src="{% static '/js/tabs.js'%}"></script>
  <script src="{% static '/js/popup.js'%}"></script>
  <script src="{% static '/js/custom.js'%}"></script>


  </body>

</html>